[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/whatsapp"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
port = 3000

[variables]
# Application Configuration
APP_PORT = "3000"
APP_DEBUG = "false"
APP_OS = "WhatsApp Business System"
APP_BASIC_AUTH = "admin:changeme123"
APP_CHAT_FLUSH_INTERVAL = "30"

# WhatsApp Features
WHATSAPP_CHAT_STORAGE = "true"
WHATSAPP_ACCOUNT_VALIDATION = "true"
WHATSAPP_AUTO_REPLY = "Thank you for contacting us. We will respond shortly."

# Performance Settings
NODE_ENV = "production"
NODE_TLS_REJECT_UNAUTHORIZED = "0"

# Note: DB_URI will be automatically set from DATABASE_URL
# Webhook settings can be added later through Railway dashboard
