[build]
builder = "dockerfile"
dockerfilePath = "docker/golang.Dockerfile"

[deploy]
startCommand = "/app/whatsapp rest"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 300

[[services]]
name = "whatsapp-go"
port = 3000